# Generated by Django 4.1.5 on 2023-02-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_gradebook_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradebook",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
